name: Publish npm package

on:
  push:
    branches:
      - main # This specifies that the action should only trigger on pushes to the main branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest # Specifies the type of machine to run the job on

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2 # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14" # Specify the version of Node.js you want to use
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci # Installs node modules and ensures a clean install

      - name: Run tests
        run: npm test # Replace with your test script

      - name: Publish to npm
        run: npm publish # Publishes your package to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Uses the npm token from your repository's secrets
